manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    #- name: luberry
    #  url-base: https://github.com/luberry
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    #- name: zmk
    #  remote: luberry
    #  revision: pmw3389
    #  import: app/west.yml
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
  self:
    path: config
